version: "3.8"
services:
  demo-spring-webflux:
    build: ./
    ports:
      - "8080:3000"
    environment:
      - MOVIE_INFO_SERVICE_PORT=3000
      - MOVIE_REVIEW_SERVICE_PORT=3001
      - MONGODB_URI=mongodb://user:pass@mongo:27017/?authMechanism=SCRAM-SHA-1
      - MOVIE_INFO_SERVICE_MONGODB_DATABASE=movie_info
      - MOVIE_REVIEW_SERVICE_MONGODB_DATABASE=movie_review
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27000:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
