version: "3.8"
services:
  demo-spring-webflux:
    build: ./
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://user:pass@mongo:27017/?authMechanism=SCRAM-SHA-1
      - MONGODB_DATABASE=DEMO_SPRING_WEBFLUX
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27000:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
